force-app/main/default/objects/OOE_Event__e/OOE_Event__e.object-meta.xml
<CustomObject>
    <label>OOE Event</label>
    <pluralLabel>OOE Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/OOE_Event__e/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OOE_Message__c/OOE_Message__c.object-meta.xml
<CustomObject>
    <label>OOE Message</label>
    <nameField>
        <displayFormat>OOEM-{0000}</displayFormat>
        <label>OOE Message</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OOE Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/OOEEvent.cls
public class OOEEvent {
    @InvocableMethod(label='Send OOE Event')
    public static void send(List<SenderDataType> sdt) {
        OOE_Event__e ooee = new OOE_Event__e(Tool__c=sdt[0].tool, Message__c=Constants.MESSAGE_BASE +
                                            sdt[0].count);
        EventBus.publish(ooee);
    }
    
    public static void afterInsert(List<OOE_Event__e> ooees){
        List<OOE_Message__c> ooems = new List<OOE_Message__c>();
        
        for(OOE_Event__e ooee : ooees) {
            ooems.add(new OOE_Message__c(Tool__c=ooee.Tool__c, Message__c=ooee.Message__c));
        }
        
        insert ooems;
    }
}