force-app/main/default/objects/OOE_Demo_Parent__c/OOE_Demo_Parent__c.object-meta.xml
<CustomObject>
    <label>OOE Demo Parent</label>
    <nameField>
        <displayFormat>OOEDP-{0000}</displayFormat>
        <label>OOE Demo Parent</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OOE Demo Parents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OOE_Demo_Parent__c/fields/Total_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Count__c</fullName>
    <label>Total Count</label>
    <summarizedField>OOE_Demo__c.Count__c</summarizedField>
    <summaryForeignKey>OOE_Demo__c.Parent__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OOE_Event__e/OOE_Event__e.object-meta.xml
<CustomObject>
    <label>OOE Event</label>
    <pluralLabel>OOE Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/OOE_Event__e/fields/Tool__c.field-meta.xml
<CustomField>
    <fullName>Tool__c</fullName>
    <label>Tool</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OOEDemoParentTrigger_Helper.cls
public class OOEDemoParentTrigger_Helper {
    public static void beforeUpdate(OOE_Demo_Parent__c newOOEDemoParent) {
        OOE_Event__e ooee = new OOE_Event__e(Tool__c='BEFORE_UPDATE TRIGGER ON OOE_Demo_Parent__c',
                                             Message__c=Constants.PARENT_MESSAGE_BASE +
                                             Integer.valueOf(newOOEDemoParent.Total_Count__c));
        EventBus.publish(ooee);
    }
}